### ISSUE TITLE
Rhino Automation - Update manual created test case (which run successfully) as "retest" 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-gurock#12]
![image](https://user-images.githubusercontent.com/70174048/98597445-baafc700-22e1-11eb-8d60-a33ac4cd4235.png)

**Comment by gravity-api** [comment]
Not a bug.
Tests which are inconclusive gets the default or the closest state to inconclusive - under TestRail it is the Retest value.
