### ISSUE TITLE
Bug manager- Execute TC on Rhino automation which passes, Jira comments has been created on the wrong execution ID in the closed bug

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-gurock#14]
![image](https://user-images.githubusercontent.com/70174048/98854698-91b73f80-2463-11eb-92c7-1b9e26e6db64.png)

![image](https://user-images.githubusercontent.com/70174048/98854533-59affc80-2463-11eb-82a3-4f3653c6d18c.png)

**Comment by gravity-api** [comment]
Not a bug
